#!/usr/bin/env python3
"""Fail the tree when a hand-written sentence disagrees with the data it describes.

Three kinds of drift have actually happened here, which is why each is checked:

  1. A rendered file falls behind its JSON. Every .md generated by tools/ is re-rendered into a
     temporary copy of the tree and compared byte for byte; the repository is never written to.
  2. A TYPED COUNT goes stale or was never right. D19's action text undercounted the open citation
     rows (it omitted C1-gotsman), and its replacement overcounted them (it called C10 and C12
     UNVERIFIED after later rows had moved them to SEARCH and PARTIAL). Counts now come from
     tools/citation_status.py, D19 carries the derived lists, and they are asserted here.
  3. A cross-reference points at nothing. Debt ids are quoted all over the tree; a reference to a
     debt that does not exist reads as provenance and is not.
  4. A CITED FILE PATH DOES NOT EXIST. Claim-2's RESULT_GAP_v2.md opened with "Response stored at
     `sources/GAP_V2_RESPONSE_RAW.md`" and that file was never written; the citation sat in a
     pushed commit for a day, reading exactly like a receipt. Same defect class as a number that
     cannot fall: it looks like evidence and nothing can make it fail.

Exit 0 and a list of what was checked, or exit 1 naming the disagreement.
"""
from __future__ import annotations
import json, pathlib, re, shutil, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import citation_status                                   # noqa: E402

RENDERS = {"render_citations.py": "CITATIONS.md",
           "render_debts.py": "DEBTS.md",
           "render_ledger.py": "LEDGER.md"}
DATA = ("citations.json", "debts.json", "ledger.json")

fail: list[str] = []
did: list[str] = []


def check_renders() -> None:
    with tempfile.TemporaryDirectory() as td:
        tmp = pathlib.Path(td)
        shutil.copytree(ROOT / "tools", tmp / "tools")
        for f in DATA:
            shutil.copy(ROOT / f, tmp / f)
        # The debts caveat is generated from the ITEM files as well as from citations.json, so the
        # temporary tree needs them or the fresh render would differ for the wrong reason.
        for d in ("cases", "twins", "controls"):
            shutil.copytree(ROOT / "p1-retrodiction" / d, tmp / "p1-retrodiction" / d)
        for script, out in RENDERS.items():
            r = subprocess.run([sys.executable, str(tmp / "tools" / script)],
                               capture_output=True, text=True)
            if r.returncode != 0:
                fail.append(f"{script} exited {r.returncode}: {r.stderr.strip().splitlines()[-1:]}")
                continue
            fresh = (tmp / out).read_text(encoding="utf-8")
            live = (ROOT / out).read_text(encoding="utf-8") if (ROOT / out).exists() else ""
            if fresh != live:
                fail.append(f"{out} is STALE: re-run tools/{script}")
            else:
                did.append(f"{out} matches a fresh render of its JSON")


def check_derived_counts() -> None:
    st = citation_status.load(ROOT)
    debts = json.loads((ROOT / "debts.json").read_text(encoding="utf-8"))
    d19 = next((x for x in debts["debts"] if x["id"] == "D19"), None)
    if d19 is None or "derived" in d19 and not isinstance(d19.get("derived"), dict):
        fail.append("D19 has no derived block to check")
        return
    dv = d19.get("derived", {})
    for key, got in (("unverified", st["unverified"]), ("below_primary", st["below_primary"])):
        if sorted(dv.get(key, [])) != sorted(got):
            fail.append(f"D19.derived.{key} says {dv.get(key)} but citations.json says {got}")
        else:
            did.append(f"D19.derived.{key} == citations.json ({', '.join(got) or 'none'})")

    # A standing caveat may not TYPE a count of citation rows; it must carry the generator marker.
    for g in debts["global"]:
        if g.startswith("{{GENERATED:"):
            continue
        if re.search(r"\b\d+\s+(rows|claims)\b", g) or re.search(r"\b\d+\s+(VERIFIED|UNVERIFIED)\b", g):
            fail.append(f"standing caveat types a citation count instead of generating it: {g[:70]}...")
    did.append("no standing caveat types a citation count")


def check_debt_refs() -> None:
    debts = json.loads((ROOT / "debts.json").read_text(encoding="utf-8"))
    known = {x["id"] for x in debts["debts"]}
    referenced: dict[str, set[str]] = {}
    for p in sorted(ROOT.rglob("*")):
        if p.is_dir() or p.suffix not in (".md", ".json", ".py") or "__pycache__" in p.parts:
            continue
        if p.name in RENDERS.values():          # generated; their source is checked instead
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        # Any D<number> token anywhere in the tree is a debt reference: the tree uses no other
        # D-numbering, and all 32 currently resolve.
        for m in re.finditer(r"\bD([1-9]\d*)\b", text):
            referenced.setdefault("D" + m.group(1), set()).add(str(p.relative_to(ROOT)))
    for ref, where in sorted(referenced.items()):
        if ref not in known:
            fail.append(f"{ref} is referenced in {', '.join(sorted(where))} but is not in debts.json")
    did.append(f"{len(referenced)} debt references resolve ({len(known)} debts on file)")


def check_citation_refs() -> None:
    st = citation_status.load(ROOT)
    known = set(st["latest"])
    debts = (ROOT / "debts.json").read_text(encoding="utf-8")
    missing = {m.group(1) for m in re.finditer(r"\brow ([CNO]\d+[\w-]*)\b", debts)} - known
    if missing:
        fail.append(f"debts.json cites citation rows that do not exist: {sorted(missing)}")
    else:
        did.append("every citation row cited by id in debts.json exists")


def check_item_sources() -> None:
    """Every source flag in an item file must name the row it stands on, or say it stands on none.

    D33 was opened when control 14's three sources all said `verified: false` while row C14 stood
    VERIFIED and had been adjudicated on them. The invariant is one-directional on purpose:
    `verified: true` REQUIRES a linked row whose status begins VERIFIED or CORRECTED, while
    `verified: false` beside a VERIFIED row is legitimate and common -- a row often covers a
    NEIGHBOURING claim (case 13's row verifies Dinur, not Arora-Safra; C4 verifies that nobody states
    the threshold). What is never allowed is a flag with no stated basis.
    """
    st = citation_status.load(ROOT)
    latest = st["latest"]
    ok_true = {"VERIFIED", "CORRECTED"}
    n = 0
    unrowed_true: list[str] = []
    rowed_false: list[str] = []
    for f in sorted((ROOT / "p1-retrodiction").glob("*/*.json")) + \
             sorted((ROOT / "p1-retrodiction").glob("cases/*/before.json")):
        if f.parent.name in ("heldout", "schema", "calibration", "prospective", "ceilings") \
                or f.stem == "REJECTED":
            continue                    # a schema DESCRIBES these keys; it does not carry a flag
        try:
            doc = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        stack = [(doc, "")]
        while stack:
            cur, path = stack.pop()
            if isinstance(cur, dict):
                if "cite" in cur and "verified" in cur:
                    n += 1
                    where = f"{f.relative_to(ROOT)} {path or '.'}"
                    if "basis" not in cur or not str(cur.get("basis", "")).strip():
                        fail.append(f"{where}: source flag with no `basis`")
                    if "citation_row" not in cur:
                        fail.append(f"{where}: source flag with no `citation_row` (use null for none)")
                        continue
                    row = cur["citation_row"]
                    if row is not None and row not in latest:
                        fail.append(f"{where}: citation_row {row!r} is not in citations.json")
                    elif cur["verified"] and row is None:
                        unrowed_true.append(where)
                    elif cur["verified"] and citation_status.tier(latest[row]["status"]) not in ok_true:
                        fail.append(f"{where}: verified: true but row {row} is "
                                    f"{latest[row]['status']}")
                    elif (not cur["verified"]) and row is not None and \
                            citation_status.tier(latest[row]["status"]) in ok_true:
                        rowed_false.append(where)
                for k, v in cur.items():
                    stack.append((v, f"{path}.{k}" if path else k))
            elif isinstance(cur, list):
                for i, v in enumerate(cur):
                    stack.append((v, f"{path}[{i}]"))
    did.append(f"{n} item source flags all name a row or state that none covers them")
    if unrowed_true:
        did.append(f"{len(unrowed_true)} flag(s) are verified: true on a DECLARED basis with no row "
                   f"({', '.join(sorted(x.split()[0].split('/')[-1] for x in unrowed_true))}) -- each "
                   f"says so in `basis`; see D33")
    if rowed_false:
        did.append(f"{len(rowed_false)} flag(s) stay false beside a VERIFIED row, because the row "
                   f"covers a neighbouring claim -- each says which in `basis`")


PATH_TOKEN = re.compile(r"`([A-Za-z0-9_][A-Za-z0-9_./-]*\.(?:md|py|json|jsonl))`")


def _is_ignored(path: pathlib.Path) -> bool:
    """True if git is told to ignore this path.

    A regenerable intermediate named in .gitignore is not a broken citation. Claim-2's
    leanboard/README.md documents `s/kinds.json` as the output of a script, and .gitignore says
    it is a 45 MB regenerable file; the citation is a build description, not a receipt. The check
    cannot read that difference off the prose, so it reads it off the tree owner's own statement
    of intent.
    """
    try:
        return subprocess.run(["git", "check-ignore", "-q", str(path)],
                              cwd=path.parent if path.parent.exists() else ROOT,
                              capture_output=True).returncode == 0
    except OSError:
        return False


def dangling_citations(root: pathlib.Path) -> list[tuple[str, str]]:
    """Backtick-quoted paths whose FIRST SEGMENT exists but whose full path does not.

    The first-segment rule is what keeps this usable across a tree that legitimately cites other
    repositories: a path is only checked if its first segment names something that exists at one
    of the reading positions. `hadamard/findings/FINDING_05.md` lives in Cooperative-AI-Defense
    and is skipped, because no `hadamard/` exists here. But `p1-retrodiction/d35/SHEET.md` is
    enforced down to the filename, because `p1-retrodiction/` is right here -- and that is
    exactly where a typo or an unwritten file hides.

    Resolution follows the reader, not the interpreter: a citation resolves if it lands from the
    containing file's directory or ANY ancestor of it up to the tree root. That is deliberate.
    `p1-retrodiction/heldout/README.md` says `tools/pack.py` and means
    `p1-retrodiction/tools/pack.py`, which anybody working in that subtree finds immediately;
    flagging it would be pedantry. A citation no ancestor can resolve is a different thing.
    """
    bad = []
    for md in sorted(root.rglob("*.md")):
        if any(part in {".git", "__pycache__"} for part in md.parts):
            continue
        bases = [md.parent, *md.parent.parents]
        bases = [b for b in bases if root in b.parents or b == root or b == root.parent]
        for cited in sorted(set(PATH_TOKEN.findall(md.read_text()))):
            head = cited.split("/", 1)[0]
            anchored = [b for b in bases if (b / head).exists()]
            if not anchored:
                continue                          # not a path into this tree; nothing to check
            if any((b / cited).exists() for b in anchored):
                continue
            if any(_is_ignored(b / cited) for b in anchored):
                continue                          # deliberately uncommitted: intent is on record
            bad.append((str(md.relative_to(root)), cited))
    return bad


def check_cited_paths_resolve() -> None:
    bad = dangling_citations(ROOT)
    for where, cited in bad:
        fail.append(f"{where} cites `{cited}`, whose directory exists here and whose file does not")
    if not bad:
        did.append("every backtick-quoted path whose first segment is in this tree resolves")


def check_debt_states() -> None:
    """Every debt carries an explicit state, and the rendered count comes from that field.

    The old count was inferred from the status STRING, so the moment a status stopped reading "open"
    while the work was still live -- which is what happened to D19, D31, D32 -- the number in
    DEBTS.md silently fell. It read 6 open when 13 were live.
    """
    debts = json.loads((ROOT / "debts.json").read_text(encoding="utf-8"))["debts"]
    allowed = {"open", "closed", "standing"}
    bad = [x["id"] for x in debts if x.get("state") not in allowed]
    if bad:
        fail.append(f"debts with a missing or invalid `state`: {', '.join(bad)}")
        return
    n = {k: sum(1 for x in debts if x["state"] == k) for k in sorted(allowed)}
    did.append(f"all {len(debts)} debts carry a state ({n['open']} open, {n['closed']} closed, "
               f"{n['standing']} standing), and DEBTS.md counts them from the field")


def check_move_kind_second_reading() -> None:
    """`move_kind` carries a second, blind reading on every item, and the disagreements survive.

    move_kind is the binding conjunct of the transformable-board screen and was assigned by one
    instance for D9. D35 measured it against a blind rater: kappa 0.430 on the 15 items whose text
    does not state its own answer, with all six disagreements running one way (mine = formula).
    This gate exists so the field cannot silently revert to looking single-rater, and so nobody
    "fixes" the 6 disagreements by overwriting one column with the other -- that would delete the
    only measurement of the field there is.
    """
    n = agree = 0
    missing, resolved = [], []
    for f in sorted(list((ROOT / "p1-retrodiction" / "cases").glob("*/before.json"))
                    + list((ROOT / "p1-retrodiction" / "controls").glob("*.json"))):
        d = json.loads(f.read_text(encoding="utf-8"))
        mk = d.get("move_kind")
        if not mk:
            continue
        n += 1
        sr = mk.get("second_reading")
        if not sr:
            missing.append(d["id"])
            continue
        if sr.get("agrees_with_first") != (sr.get("kind") == mk.get("kind")):
            resolved.append(d["id"])
        agree += bool(sr.get("agrees_with_first"))
    if missing:
        fail.append(f"move_kind with no second reading (see p1-retrodiction/d35): "
                    f"{', '.join(missing)}")
        return
    if resolved:
        fail.append(f"a second reading's `agrees_with_first` no longer matches its own codes, so a "
                    f"column was edited after the fact: {', '.join(resolved)}")
        return
    if n and agree == n:
        fail.append("every move_kind second reading now agrees with the first: the six D35 "
                    "disagreements have been overwritten, which deletes the measurement")
        return
    did.append(f"all {n} move_kind fields carry a blind second reading, and {n - agree} "
               f"disagreement(s) are preserved (D35: kappa 0.430 on the codable 15)")


def main() -> int:
    check_renders()
    check_derived_counts()
    check_debt_refs()
    check_citation_refs()
    check_item_sources()
    check_move_kind_second_reading()
    check_debt_states()
    check_cited_paths_resolve()
    for d in did:
        print(f"  ok      {d}")
    for f in fail:
        print(f"  FAILED  {f}")
    if fail:
        print(f"\n{len(fail)} disagreement(s) between prose and data.")
        return 1
    print(f"\nOK ({len(did)} checks).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
