#!/usr/bin/env python3
"""Build the D35 blind rating sheet for `move_kind`, DERIVED from the case files.

D35: `move_kind` is the binding conjunct of the transformable-board screen -- the
conjunct that makes it selective -- and it was assigned by one instance, for D9,
with no second reading. This builds the sheet from the record itself so no move
text is authored by me, records the scramble so the run is reproducible, and
flags the items whose recorded text CONTAINS ITS OWN ANSWER.

Outputs (all derived; do not hand-edit):
  d35/SHEET.md          the pasteable sheet, answers withheld
  d35/key.json          my assignment, the scramble, and the giveaway flags
"""
import glob, json, os, random

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SEED = 35            # fixed and recorded, so the order is reproducible

GIVEAWAY = ("formula", "explicit", "existence", "exists", "asserted")


def move_text(d):
    """The move as the RECORD states it, with provenance. Never paraphrased."""
    bb = d.get("before_board") or {}
    if bb.get("M"):
        return bb["M"], "before_board.M"
    b = d.get("board") or {}
    if b.get("M"):
        return b["M"], "board.M"
    # no move slot anywhere: give the rater the rest of the board, and say so
    src = bb or b
    parts = [f"{k} = {v}" for k, v in src.items() if k in ("name", "S", "I", "C", "T") and v]
    return None, "; ".join(parts) or "nothing but the problem name"


def main():
    files = sorted(glob.glob(os.path.join(ROOT, "cases", "*", "before.json"))) + \
            sorted(glob.glob(os.path.join(ROOT, "controls", "*.json")))
    items = []
    for f in files:
        d = json.load(open(f))
        mk = d.get("move_kind") or {}
        mv, prov = move_text(d)
        shown = mv if mv else f"NO MOVE SLOT RECORDED. The rest of the board reads: {prov}"
        items.append({
            "id": d["id"], "problem": d.get("problem"),
            "shown": shown,
            "provenance": prov if mv else "no move slot",
            "rater1": mk.get("kind"),
            "rater1_reason": mk.get("reason"),
            "giveaway": sorted(w for w in GIVEAWAY if w in shown.lower()),
        })
    assert len(items) == 17, len(items)

    order = list(range(len(items)))
    random.Random(SEED).shuffle(order)

    lines = ["# D35 — blind rating sheet: `move_kind`, one field, 17 items", "",
             "Generated by `d35/build_sheet.py` from the case files. Do not hand-edit.", "",
             "You are rating ONE property of 17 proof strategies. Do not use any tools: no file",
             "reads, no web access, no code execution, no searching. Answer from the text below",
             "plus your own knowledge.", "",
             "**The question, for each item:** is the move a **FORMULA** that is carried out, or",
             "an **EXISTENCE THEOREM** that asserts a good object exists?", "",
             "Answer with exactly one of:", "",
             "* `FORMULA` — the move is computed or written down; nothing has to be shown to exist first.",
             "* `EXISTENCE-THEOREM` — a legal move requires some object to be shown to exist.",
             "* `NO MOVE RECORDED` — the text does not describe a move at all. This is a legitimate",
             "  answer and you should use it rather than guess.", "",
             "Give a one-line reason for each. The reasons are read before the codes are scored.",
             "Do not try to identify which project this is or what the expected answers are.", "",
             "---", ""]
    for n, idx in enumerate(order, 1):
        it = items[idx]
        lines += [f"**{n}. {it['problem']}**", "", f"> {it['shown']}", ""]
    lines += ["---", "",
              "Finish with a table: item number, your code, and your one-line reason."]
    open(os.path.join(HERE, "SHEET.md"), "w").write("\n".join(lines) + "\n")

    key = {"label": "D35_KEY",
           "seed": SEED,
           "order_shown_to_rater": [items[i]["id"] for i in order],
           "rater1": {it["id"]: it["rater1"] for it in items},
           "rater1_reasons": {it["id"]: it["rater1_reason"] for it in items},
           "shown_text": {it["id"]: it["shown"] for it in items},
           "provenance": {it["id"]: it["provenance"] for it in items},
           "self_answering": {it["id"]: it["giveaway"] for it in items if it["giveaway"]},
           "counts_rater1": {}}
    for it in items:
        key["counts_rater1"][it["rater1"]] = key["counts_rater1"].get(it["rater1"], 0) + 1
    json.dump(key, open(os.path.join(HERE, "key.json"), "w"), indent=1, ensure_ascii=False)
    open(os.path.join(HERE, "key.json"), "a").write("\n")

    print("SHEET.md and key.json written")
    print("rater 1 counts:", key["counts_rater1"])
    print("items whose SHOWN TEXT contains a giveaway word:")
    for k, v in key["self_answering"].items():
        print(f"  {k}: {v}")
    print("items with no move slot:",
          [i for i, p in key["provenance"].items() if p == "no move slot"])


if __name__ == "__main__":
    main()
