"""The 2^(6-2) fractional factorial (E = ABC, F = BCD, resolution IV) plus four controls.

Generated by the same algorithm as the artifact; tests/test_fidelity.py asserts the arm list,
levels, ids and labels match the artifact's exactly.
"""
from __future__ import annotations
from dataclasses import dataclass, field

BLOCK_IDS = ("A", "B", "C", "D", "E", "F")


@dataclass(frozen=True)
class Arm:
    id: str
    kind: str                      # fact | pfmt | prig | ef | schema
    label: str
    lv: dict[str, int] | None = None
    on: str | None = None

    def present(self, block: str) -> bool:
        """Is this block in this arm's prompt? Controls are not on the factorial grid."""
        if self.kind == "fact":
            return self.lv[block] > 0
        if self.kind in ("ef", "schema"):
            return block in ("E", "F")
        return False


def _build() -> list[Arm]:
    arms: list[Arm] = []
    k = 0
    for a in (-1, 1):
        for b in (-1, 1):
            for c in (-1, 1):
                for d in (-1, 1):
                    lv = {"A": a, "B": b, "C": c, "D": d, "E": a * b * c, "F": b * c * d}
                    on = "".join(x for x in BLOCK_IDS if lv[x] > 0)
                    k += 1
                    label = ("full v2.1" if on == "ABCDEF" else f"blocks {on}") if on else "bare"
                    arms.append(Arm(id=f"X{k:02d}", kind="fact", label=label, lv=lv, on=on))
    arms += [
        Arm(id="PFMT", kind="pfmt", label="placebo, formatting rules"),
        Arm(id="PRIG", kind="prig", label="placebo, generic rigour"),
        Arm(id="EFON", kind="ef", label="E+F only, as prose"),
        Arm(id="EFSC", kind="schema", label="E+F as return fields"),
    ]
    return arms


ARMS: list[Arm] = _build()
BY_ID: dict[str, Arm] = {a.id: a for a in ARMS}
BARE = next(a for a in ARMS if a.on == "")
FULL = next(a for a in ARMS if a.on == "ABCDEF")


def arm_by_id(arm_id: str) -> Arm:
    return BY_ID[arm_id]
