"""Frozen stimulus text, extracted from the original browser artifact.

blocks.json is generated by tools/extract_from_artifact.mjs, which *evaluates* the artifact's own
JavaScript rather than re-typing it. tests/test_fidelity.py regenerates it and asserts equality, so
a drift between this port and the artifact fails the test suite instead of passing silently.
"""
from __future__ import annotations
import json, pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_D = json.loads((_HERE / "blocks.json").read_text(encoding="utf-8"))

BLOCKS: dict[str, str] = _D["BLOCKS"]          # A..F, in order
SCHEMA: str = _D["SCHEMA"]                     # the return-fields arm
PFMT_ARTIFACT: str = _D["PFMT"]                # the artifact's 10-paragraph placebo seeds,
PRIG_ARTIFACT: str = _D["PRIG"]                # kept for provenance; NOT used (see placebo.py)
PRED_TEXT: dict[str, str] = _D["PRED_TEXT"]
BATTERY0: list[dict] = _D["BATTERY0"]
FULL_LEN: int = _D["FULL_LEN"]                 # 10121: the length the placebos match
_CORE_TEMPLATE: str = _D["CORE_TEMPLATE"]
_JUDGE_TEMPLATE: str = _D["JUDGE_TEMPLATE"]

BLOCK_IDS = ("A", "B", "C", "D", "E", "F")
JUDGE_TRUNCATION = 40_000                      # the artifact's text.slice(0, 40000)


def core(words: int) -> str:
    """The fixed return menu appended to every arm, bare included."""
    return _CORE_TEMPLATE.replace("%%W%%", str(words))


def judge_prompt(problem: dict, text: str) -> str:
    """The artifact's judge prompt, verbatim. Extra fields are appended by prompts.py."""
    return (_JUDGE_TEMPLATE
            .replace("%%STATEMENT%%", problem["statement"])
            .replace("%%TRUTH%%", problem["truth"])
            .replace("%%RESPONSE%%", text[:JUDGE_TRUNCATION]))
